[global]
   workgroup = CORP
   server string = ws01
   security = user
   map to guest = Never
   server min protocol = NT1
   log level = 1

[secret]
   comment = Sauvegarde locale (Administrateurs uniquement)
   path = /srv/secret
   valid users = Administrator
   read only = yes
   browseable = yes
