[global]
   workgroup = CORP
   server string = files01
   security = user
   map to guest = Never
   server min protocol = NT1
   log level = 1

[finance]
   comment = Partage finance (accès restreint)
   path = /srv/finance
   valid users = svc-sql
   read only = yes
   browseable = yes
